name = "Mittelerde"
author = "HannesGitHub"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00c6366f6b2509d724490824ed90f22142dd04dd3d979d29885930deca468608"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
