name = "createHome"
author = "hannesgith"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6da739eff06d63e7b142167ed9304a7222a720fe771a9ad5a3cc7c89316261fa"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
